### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by theerfan** [ViRb3/de4dot-cex#13] opened 2020-03-09 12:33 UTC
Hi.
I'm using Visual Studio 2019, and trying to build the x64 project which I cloned directly with the instruction given in the original repo, but it gives me the following exception: 

> BadImageFormatException: Could not load file or assembly 'de4dot.code, Version=3.1.41592.3405, Culture=neutral, PublicKeyToken=d3f3ed1e47f67fc6' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Even though the de4dot.code project is right there alongside the rest.

I also tried to download the release zip file but it returns the following:

> Unhandled Exception: System.BadImageFormatException: Invalid DOS signature
>    at dnlib.PE.ImageDosHeader..ctor(IImageStream reader, Boolean verify) in D:\a\de4dot-cex\de4dot-cex\dnlib\src\PE\ImageDosHeader.cs:line 30
>    at dnlib.PE.PEInfo..ctor(IImageStream reader, Boolean verify) in D:\a\de4dot-cex\de4dot-cex\dnlib\src\PE\PEInfo.cs:line 44
>    at dnlib.PE.PEImage..ctor(IImageStreamCreator imageStreamCreator, ImageLayout imageLayout, Boolean verify) in D:\a\de4dot-cex\de4dot-cex\dnlib\src\PE\PEImage.cs:line 134
>    at dnlib.PE.PEImage..ctor(String fileName, Boolean mapAsImage, Boolean verify) in D:\a\de4dot-cex\de4dot-cex\dnlib\src\PE\PEImage.cs:line 165
>    at de4dot.code.ObfuscatedFile.UnpackNativeImage(IEnumerable`1 deobfuscators) in D:\a\de4dot-cex\de4dot-cex\de4dot.code\ObfuscatedFile.cs:line 193
>    at de4dot.code.ObfuscatedFile.LoadModule(IEnumerable`1 deobfuscators) in D:\a\de4dot-cex\de4dot-cex\de4dot.code\ObfuscatedFile.cs:line 182
>    at de4dot.code.ObfuscatedFile.Load(IList`1 deobfuscators) in D:\a\de4dot-cex\de4dot-cex\de4dot.code\ObfuscatedFile.cs:line 161
>    at de4dot.cui.FilesDeobfuscator.DotNetFileLoader.Add(IObfuscatedFile file, Boolean skipUnknownObfuscator, Boolean isFromPossibleFiles) in D:\a\de4dot-cex\de4dot-cex\de4dot.cui\FilesDeobfuscator.cs:line 246
>    at de4dot.cui.FilesDeobfuscator.DotNetFileLoader.CreateObfuscatedFile(SearchDir searchDir, String filename) in D:\a\de4dot-cex\de4dot-cex\de4dot.cui\FilesDeobfuscator.cs:line 347
>    at de4dot.cui.FilesDeobfuscator.DotNetFileLoader.<LoadFiles>d__7.MoveNext() in D:\a\de4dot-cex\de4dot-cex\de4dot.cui\FilesDeobfuscator.cs:line 275
>    at de4dot.cui.FilesDeobfuscator.DotNetFileLoader.<Load>d__5.MoveNext() in D:\a\de4dot-cex\de4dot-cex\de4dot.cui\FilesDeobfuscator.cs:line 203
>    at de4dot.cui.FilesDeobfuscator.<LoadAllFiles>d__11.MoveNext() in D:\a\de4dot-cex\de4dot-cex\de4dot.cui\FilesDeobfuscator.cs:line 167
>    at de4dot.cui.FilesDeobfuscator.DetectObfuscators() in D:\a\de4dot-cex\de4dot-cex\de4dot.cui\FilesDeobfuscator.cs:line 99
>    at de4dot.cui.Program.Main(String[] args) in D:\a\de4dot-cex\de4dot-cex\de4dot.cui\Program.cs:line 118
>    at de4dot_x64.Program.Main(String[] args) in D:\a\de4dot-cex\de4dot-cex\de4dot-x64\Program.cs:line 23
With both the de4dot.exe and de4dot-64.exe.

**Comment by ViRb3** [comment] 2020-03-09 16:29
From your log:
> BadImageFormatException: Could not load file or assembly 'de4dot.code, Version=3.1.41592.3405, Culture=neutral, PublicKeyToken=d3f3ed1e47f67fc6' or one of its dependencies. __An attempt was made to load a program with an incorrect format.__

You are trying to build de4dot.code for an unsupported architecture. Note that many of de4dot's sub-projects compile for x86 only, but they will still work just fine on x64. That said, if you leave the build settings as default (Mixed Platforms), everything should compile successfully, or at least it does here, on the CI server, and for everybody else.

**Comment by theerfan** [comment] 2020-03-09 16:34
![image](https://user-images.githubusercontent.com/11455681/76235976-2caaaa80-6241-11ea-821a-c0e2a986de1b.png)

I never even touched the build settings.

**Comment by ViRb3** [comment] 2020-03-09 16:42
Do you have .NET 2.0 installed? Seems like that's all sub-projects target. Unfortunately, I cannot reproduce this issue on my end or at [GitHub's CI](https://github.com/ViRb3/de4dot-cex/blob/master/.github/workflows/main.yml).

**Comment by theerfan** [comment] 2020-03-09 16:48
Alright, thank you.

**Comment by ViRb3** [comment] 2020-03-09 16:59
Turns out I had accidentally made de4dot.code x86-only for Debug mode, which makes it unusable from de4dot-x64. This did not affect Release mode, so the CI and everything else was unaffected. I pushed a fix, please try it out and let me know how it goes.

Thanks for reporting!

**Comment by theerfan** [comment] 2020-03-09 17:38
Yeah, it compiles now but I'm encountering this other problem. xD
When I run:

> de4dot-x64 Program.exe

I get:

> Array dimensions exceeded supported range.
> Array dimensions exceeded supported range.
> Detected ConfuserEx v0.6.0 (G:\Blah\de4dot-cex\Debug\Program.exe)
> Cleaning G:\Blah\de4dot-cex\Debug\Program.exe
> 
> Unhandled Exception: System.ApplicationException: Invalid new target, it's null

**Comment by ViRb3** [comment] 2020-03-09 17:39
Can you confirm that it also happens with the [pre-built binaries](https://github.com/ViRb3/de4dot-cex/releases)? If yes, please open a separate issue for that problem.

**Closed by ViRb3** 2020-03-09 17:39 UTC
Labels: bug

**Comment by theerfan** [comment] 2020-03-09 17:44
I will, but it's also worth mentioning that now the Release config won't compile. 
![image](https://user-images.githubusercontent.com/11455681/76241829-d6db0000-624a-11ea-8aef-74994012efb8.png)

**Comment by ViRb3** [comment] 2020-03-09 17:47
[GitHub CI](https://github.com/ViRb3/de4dot-cex/runs/495727838) can compile it, and so can I. try to clean your project maybe?

**Comment by theerfan** [comment] 2020-03-09 17:50
I cleaned the entire solution and tried again, still the same results.
![image](https://user-images.githubusercontent.com/11455681/76242273-ab0c4a00-624b-11ea-86d2-25f3967d9e46.png)

**Comment by ViRb3** [comment] 2020-03-09 17:59
Your output log suggests 17 succeeded and 0 failed builds, so there should be no problems.

**Comment by theerfan** [comment] 2020-03-09 18:04
> 
> 
> I will, but it's also worth mentioning that now the Release config won't compile.
> ![image](https://user-images.githubusercontent.com/11455681/76241829-d6db0000-624a-11ea-8aef-74994012efb8.png)

I got this again after the clean builds.
P.S: Ik it's a run-time problem but still. xD
